#ifndef MOTION_CONTROL_LIB_GLOBAL_H
#define MOTION_CONTROL_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOTION_CONTROL_LIB_LIBRARY)
#  define MOTION_CONTROL_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOTION_CONTROL_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOTION_CONTROL_LIB_GLOBAL_H
